### ISSUE TITLE
Button attribute copy and paste bug

### ISSUE THREAD

**Issue by faxwang** [DreamWall-Animation/dwpicker#59]
When I paste the attributes of another button, the attributes of the picker are refreshed in time in the picker window, but they are not refreshed in the advance edit window. 
Even if I close the advance edit window and open it again, it cannot be refreshed correctly. Then I move the copied button in the advance edit window, and the previously copied information is restored to the previous state

![image](https://user-images.githubusercontent.com/39043550/209531415-79d76799-3286-4a0b-8149-599cd23e8e21.png)

**Comment by luckylyk** [comment]
Hi, 
Firstly, sorry again for the long delay.
Secondly, thanks a lot for that short and clear report.
Thirdly, this should be fixed in release 0.6.2 !

**Comment by faxwang** [comment]
Hi,
Thanks for reply!
The problem still seems to exist. maya:2019, picker plugin version:0.6.3

I recorded the gif file and can see my operation.

![按钮的复制](https://user-images.githubusercontent.com/39043550/213401231-e7b0daaa-1e26-443f-90dd-6e2196baf8d3.gif)

**Comment by luckylyk** [comment]
this is indeed full broken
I propably had wrong stuff in memory because it was working fine at last test :/ I'm on it

**Comment by luckylyk** [comment]
Should be fixed with release 0.6.4
